"""users and pumps

Revision ID: 615d84380efd
Revises: 
Create Date: 2018-07-29 13:54:25.450151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615d84380efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('fullname', sa.String(length=12), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_fullname'), 'pump', ['fullname'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pump_fullname'), table_name='pump')
    op.drop_table('pump')
    # ### end Alembic commands ###
